/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['postLogin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSession']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/storage': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getStorage']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/metrics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getMetrics']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/wallpaper': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getWallpaper']
    put: operations['putWallpaper']
    post?: never
    delete: operations['deleteWallpaper']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/wallpaper/image': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getWallpaperImage']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/preferences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getPreferences']
    put: operations['putPreferences']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['postLogout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/cooling': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCooling']
    put: operations['setCooling']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getProfile']
    put?: never
    post: operations['updateProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/manage': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read a management view using the authenticated administrator identity */
    get: {
      parameters: {
        query: {
          view:
            | 'jobs'
            | 'storage-options'
            | 'raid-candidates'
            | 'smart'
            | 'services'
            | 'journal'
            | 'updates'
            | 'files'
            | 'nfs'
            | 'power'
          target?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Typed view result or explicit error; never shell output */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Administrator required */
        403: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    /** Preview, enqueue or cancel an operation, or clear finished job history */
    post: {
      parameters: {
        query: {
          view: 'plan' | 'run' | 'cancel' | 'clear-history'
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            /** @description Client idempotency identifier */
            id?: string
            /** @description Allowlisted domain action; arbitrary commands are rejected */
            action?: string
            params?: {
              [key: string]: unknown
            }
            /** @description Fresh preview state digest */
            fingerprint?: string
            /** @description Exact target acknowledgement from preview */
            confirmation?: string
          }
        }
      }
      responses: {
        /** @description Preview with target/details/fingerprint/confirmation */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Persistent job accepted */
        202: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Conflict or task can no longer be cancelled */
        409: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/metrics/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          hours?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description One recorded sample per minute; gaps are retained */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Metrics'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/notifications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Persistent deduplicated active and resolved alerts */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    /** Clear resolved alert and event history; active warnings remain */
    delete: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description History cleared */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Administrator required */
        403: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/terminal': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Admin user PTY WebSocket; input/resize JSON in */
        101: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/files/content': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query: {
          target: string
          /** @description Return a bounded JPEG image thumbnail instead of the original file */
          thumbnail?: '1'
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description File attachment or image/jpeg thumbnail under caller Linux UID/GID; no-store */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Access denied or thumbnail unavailable */
        403: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Thumbnail generation timed out or service unavailable */
        503: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put: {
      parameters: {
        query: {
          target: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/octet-stream': string
        }
      }
      responses: {
        /** @description Entire upload atomically published; existing files are never overwritten */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description File exists */
        409: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Identity: {
      username: string
      name: string
      uid: number
      role: string
    }
    User: {
      username: string
      name: string
      uid: number
      gid: number
      home: string
      shell: string
      category: string
      groups: string[]
    }
    Group: {
      name: string
      gid: number
      members: string[]
    }
    Accounts: {
      users: components['schemas']['User'][]
      groups: components['schemas']['Group'][]
    }
    Metrics: {
      systemTotal: number
      systemAvailable: number
      disks: {
        [key: string]: {
          read: number
          write: number
        }
      }
      network: {
        [key: string]: {
          read: number
          write: number
        }
      }
      hostname: string
      cpu: number | null
      memoryTotal: number
      memoryUsed: number
      uptime: number
      cpuTemperature: number | null
      observedAt: string
      /** @description Fan PWM duty as a percentage; null when unavailable. */
      cpuFanPercent?: number | null
      cpuFanRpm: number | null
    }
    Array: {
      missing?: number
      memberStates?: {
        [key: string]: string
      }
      reshapePending?: boolean
      syncPercent?: number
      syncSpeed?: number
      syncRemaining?: number
      name: string
      level: string
      state: string
      degraded: string
      members: string[]
      sync: string
      progress: string
      device: string
      uuid: string
      size: number
    }
    Preferences: {
      /**
       * @description Personal interface language; English is the default and fallback.
       * @default en
       * @enum {string}
       */
      language: 'en' | 'ru' | 'uk'
      taskbar?: string[]
      desktopLayouts?: {
        [key: string]: {
          id: string
          kind: string
          x: number
          y: number
        }[]
      }
      smartCrcBaselines?: {
        [key: string]: number
      }
      /** @enum {string} */
      theme: 'dark' | 'light'
      layouts: {
        [key: string]: string[]
      }
    }
    Login: {
      username: string
      password: string
    }
    Error: {
      error: string
    }
    Health: {
      status: string
      version: string
    }
    Device: {
      name: string
      kname: string
      path: string
      type: string
      size: number
      model?: string | null
      serial?: string | null
      tran?: string | null
      fstype?: string | null
      uuid?: string | null
      pkname?: string | null
      rota?: boolean
      mountpoints?: (string | null)[]
      children?: components['schemas']['Device'][]
      start?: number
      label?: string | null
    }
    Mount: {
      source: string
      target: string
      fstype: string
      options: string
      children?: components['schemas']['Mount'][]
      size?: number | null
      used?: number | null
      avail?: number | null
    }
    Storage: {
      devices: components['schemas']['Device'][]
      mounts: components['schemas']['Mount'][]
      arrays: components['schemas']['Array'][]
      observedAt: string
    }
    CoolingSettings: {
      /** @enum {string} */
      profile: 'quiet' | 'balanced' | 'performance'
      sampleSeconds: number
      /** @enum {string} */
      cpuProfile: 'quiet' | 'balanced' | 'performance'
    }
    CoolingState: {
      config: components['schemas']['CoolingSettings']
      available: boolean
      status: {
        profile: string
        dutyPercent: number
        reason: string
        observedAt: number
        disks: {
          path: string
          /** @enum {string} */
          state: 'active' | 'sleeping' | 'unknown' | 'unavailable'
          temperature: number | null
          device?: string
          /** @enum {string} */
          health?: 'passed' | 'warning' | 'failed' | 'unknown'
          stale?: boolean
          observedAt?: number | null
          warnings?: string[]
          attributes?: {
            id: number
            name: string
            raw?: {
              value?: number
              string?: string
            }
          }[]
        }[]
        cpu?: {
          available: boolean
          profile?: string
          thresholds?: number[]
        }
      }
    }
    Profile: {
      username: string
      name: string
      uid: string
      home: string
      groups: string[]
      keys: {
        id: string
        type: string
        fingerprint: string
        comment: string
      }[]
    }
    ProfileUpdate: {
      /** @enum {string} */
      action: 'name' | 'password' | 'add' | 'delete'
      name?: string
      currentPassword?: string
      newPassword?: string
      key?: string
      id?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  postLogin: {
    parameters: {
      query?: never
      header: {
        'X-PaNasMs-Request': '1'
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Login']
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Identity']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Identity']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getUsers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Accounts']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getStorage: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Storage']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getMetrics: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Metrics']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getWallpaper: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current wallpaper revision, empty when unset */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            version: string
          }
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  putWallpaper: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'image/jpeg': string
        'image/png': string
      }
    }
    responses: {
      /** @description Current wallpaper revision, empty when unset */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            version: string
          }
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  deleteWallpaper: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current wallpaper revision, empty when unset */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            version: string
          }
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getWallpaperImage: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current user's wallpaper */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/jpeg': string
        }
      }
      /** @description No wallpaper */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getPreferences: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Preferences']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  putPreferences: {
    parameters: {
      query?: never
      header: {
        'X-PaNasMs-Request': '1'
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Preferences']
      }
    }
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Preferences']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  postLogout: {
    parameters: {
      query?: never
      header: {
        'X-PaNasMs-Request': '1'
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getCooling: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cooling settings and last observed controller state */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CoolingState']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  setCooling: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CoolingSettings']
      }
    }
    responses: {
      /** @description Cooling settings and last observed controller state */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CoolingState']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Own Linux profile */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Profile']
        }
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  updateProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfileUpdate']
      }
    }
    responses: {
      /** @description Updated; password change revokes panel sessions */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Failure */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
}
